const menu = [
    {
      id: 1,
      title: 'buttermilk pancakes',
      category: 'breakfast',
      price: 15.99,
      img: './images/pancake.jpeg',
      desc: `Enjoy our pancakes with crisp exterior and soft, airy interior. They are made from thinner batter than actual cakes, and a little hot grease sets the outer surface quickly. `,
    },
    {
      id: 2,
      title: 'diner double',
      category: 'lunch',
      price: 13.99,
      img: './images/basmati.jpg',
      desc: `If you think rice is just rice, think again! Here are just a few of the reasons why Basmati is best and why it's worth choosing Basmati over ordinary rice.  `,
    },
    {
      id: 3,
      title: 'godzilla milkshake',
      category: 'beverages',
      price: 6.99,
      img: './images/milkshake2.jpeg',
      desc: `This milkshake is a combination of two of the most popular kid-friendly desserts on the planet. Oreos and milkshake together in one – who could say no to that?`,
    },
    {
      id: 4,
      title: 'country delight',
      category: 'breakfast',
      price: 20.99,
      img: './images/item-4.jpeg',
      desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
    },
    {
      id: 5,
      title: 'egg attack',
      category: 'lunch',
      price: 22.99,
      img: './images/burger1.jpeg',
      desc: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
    },
    {
      id: 6,
      title: 'sparkling wine',
      category: 'beverages',
      price: 18.99,
      img: './images/wine.jpg',
      desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
    },
    {
      id: 7,
      title: 'bacon overflow',
      category: 'breakfast',
      price: 8.99,
      img: './images/bacon.jpeg',
      desc: `Filled with streaky bacon, soft leeks and plenty of cheddar in a Marmite-laced pastry, try this quiche for a dish singing with salty, umami flavours. `,
    },
    {
      id: 8,
      title: 'american classic',
      category: 'lunch',
      price: 12.99,
      img: './images/item-8.jpeg',
      desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
    },
    {
      id: 9,
      title: 'quarantine buddy',
      category: 'beverages',
      price: 16.99,
      img: './images/item-9.jpeg',
      desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
    },
  ];
  export default menu;
  